apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-campus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Smart-Campus-Digital-Twin/Smart-Campus-Digital-Twin-v2.git
    targetRevision: Deployment
    path: deployment/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: campus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 5
