apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge
  namespace: campus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bridge
  template:
    metadata:
      labels:
        app: bridge
    spec:
      containers:
        - name: bridge
          image: ghcr.io/smart-campus-digital-twin/campus-bridge:deployment
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: campus-common
            - secretRef:
                name: campus-mqtt
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
