apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: campus

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - kafka-init.yaml
  - influxdb.yaml
  - mosquitto.yaml
  - keycloak.yaml
  - mlflow.yaml
  - api.yaml
  - bridge.yaml
  - simulator.yaml
  - frontend.yaml
  - grafana.yaml
  - kong.yaml

images:
  - name: campus-api
    newName: ghcr.io/smart-campus-digital-twin/campus-api
    newTag: Deployment
  - name: campus-bridge
    newName: ghcr.io/smart-campus-digital-twin/campus-bridge
    newTag: Deployment
  - name: campus-simulator
    newName: ghcr.io/smart-campus-digital-twin/campus-simulator
    newTag: Deployment
  - name: campus-frontend
    newName: ghcr.io/smart-campus-digital-twin/campus-frontend
    newTag: Deployment
  - name: campus-ml-training
    newName: ghcr.io/smart-campus-digital-twin/campus-ml-training
    newTag: Deployment
  - name: campus-ml-inference
    newName: ghcr.io/smart-campus-digital-twin/campus-ml-inference
    newTag: Deployment
